### ISSUE TITLE
Missing PVR libraries for VitaSDK

### ISSUE THREAD

**Issue by amg98** [GrapheneCt/PVR_PSP2#11]
In the releases, the PVR stubs for VitaSDK are missing. Does it mean we can use the ones provided in the DolceSDK release?

**Comment by GrapheneCt** [comment]
I'm not sure I understand what the issue here is and how is it related to DolceSDK, which no longer exists. If you want to use these libraries with VitaSDK, you should use stubs from vitasdk_stubs.zip, which is present in release.

**Comment by amg98** [comment]
Sorry, I should have given more details. I'm referring to the libpvr2d_stub.a and the libpvrPSP2_WSEGL_stub.a. They are included in the normal release zip but not in the vitasdk one, so I was wondering if they are needed in vitasdk or not.

**Comment by GrapheneCt** [comment]
As long as you are using only EGL, GLES1 or GLES2, those stubs are not needed.
