### ISSUE TITLE
EGL/egl.h is missing definition of IMG_CALLCONV

### ISSUE THREAD

**Issue by madebr** [GrapheneCt/PVR_PSP2#19]
The file `EGL/egl.h` defines `APIENTRY` as `IMG_CALLCONV`:
https://github.com/GrapheneCt/PVR_PSP2/blob/7f5a95d569f2d7e45ee9b69da537734d33c5db86/include/EGL/egl.h#L26-L28

But this file does not define `IMG_CALLCONV` anywhere, and does not include an external file to define it.
It is defined here:
https://github.com/GrapheneCt/PVR_PSP2/blob/7f5a95d569f2d7e45ee9b69da537734d33c5db86/include/gpu_es4/eurasia/include4/img_defs.h#L118

So I think `EGL/egl.h` is missing the following (or something similar)
```c
#include <gpu_es4/eurasia/include4/img_defs.h>
```

This causes issues when using PVR_PSP2 with the upcoming SDL3.
See https://github.com/libsdl-org/SDL/pull/7123

For SDL3, I fixed it by adding the following to `EGL/egl.h`:
```c
#ifndef IMG_CALLCONV
#define IMG_CALLCONV
#endif
```

**Comment by GrapheneCt** [comment]
Fixed by removing IMG definitions dependency.
